/*
 * This source file was generated by the Gradle 'init' task
 */
package coffee;

import java.util.ArrayList;
import java.util.List;

import coffee.model.Customer;
import coffee.service.CustomerService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}